# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=64)),
                ('PASSWORD', models.CharField(max_length=64)),
            ],
        ),
    ]
